name: Deploy Messaging to Azure Container App
#TODO: Pass in the resouce group as an input
#TODO: pass in the port as an input

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      container_app_name:
        required: true
        type: string

permissions:
  id-token: write # Required to fetch an OIDC token for Azure login.

env:
  RESOURCE_GROUP: acmetickets_rg 
  CONTAINERAPPS_ENVIRONMENT: acmeticketsacadev
  AZURE_LOCATION: eastus2

jobs:
  deploy-messaging-app:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade Azure CLI
        run: |
            sudo az upgrade --yes

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Update Messaging App
        run: |
          az containerapp update \
            --name "${{ inputs.container_app_name }}" \
            --resource-group "$RESOURCE_GROUP" \
            --image "${{ inputs.image_tag }}" \
            --set-env-vars ASPNETCORE_ENVIRONMENT=Development ConnectionStrings__AzureServiceBus='${{ secrets.AZURE_SERVICEBUS_CONNECTION_STRING }}'