name: Required Unit Tests

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.repository.full_name }}
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: ${{ runner.os }}-nuget-

    - name: Remove existing GitHub NuGet source
      run: dotnet nuget remove source github || true

    - name: Add GitHub NuGet source with GitHub Token
      run: dotnet nuget add source https://nuget.pkg.github.com/AcmeTickets/index.json --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Print working directory
      run: pwd

    - name: List test output
      run: ls -R src/Test.UnitTests/bin/Release/net9.0

    # - name: Run unit tests
    #   run: dotnet test --no-build --configuration Release --verbosity normal --logger "trx" --results-directory "TestResults"

    - name: Test
      run: dotnet test --no-restore --configuration Release --logger:"junit;LogFilePath=${{ github.workspace }}/results/test-results.xml"

      # create a test summary markdown file
      # if you don't specify an output file, it will automatically add
      # as a job summary. If you specify an output file, you have to
      # create your own step of adding it to the job summary. I am
      # intentionally doing that to show job summaries
    - name: Create test summary
      uses: test-summary/action@v2.4
      with:
        paths: ${{ github.workspace }}/results/*.xml
        output: ${{ github.workspace }}/results/summary.md
        show: "all"
      if: always()

      # I am adding the test results to the Job Summary
    - name: Add Test Results To Job Summary
      run: |
        echo "TEST RESULTS:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        cat "${{ github.workspace }}/results/summary.md" >> $GITHUB_STEP_SUMMARY
      if: always()


    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/